- include_tasks: /repos/igopythonlibs/ansible/roles/main/tasks/main.yml
  vars:
    igolibs_repodir: /repos/igopythonlibs

- apt: name={{item}} state=latest force=yes
  with_items:
  - python3
  - python3-rpi.gpio
  - python3-pygame
  - rsync
  - monit

- file: dest=/home/{{ansible_ssh_user}}/doorbell state=directory

- synchronize: src={{repodir}}/{{item}} dest=/home/{{ansible_ssh_user}}/doorbell/
  with_items:
  - SOUND_ATTRIBUTION.md
  - sound
  - README.md
  - logging.conf
  - LICENSE.txt
  - lib
  - doorbell.py
  - doorbell_config.ini
  - doorbell_runner.sh

# fix audio hiss
- lineinfile: dest=/boot/config.txt state=present line=disable_audio_dither=1

- synchronize: src={{repodir}}/monit/monitrc dest=/etc/monit/conf.d/doorbell

- name: make monit run on boot
  synchronize: src={{repodir}}/monit/monit.service dest=/lib/systemd/system/monit.service

- shell: systemctl daemon-reload
- shell: systemctl enable monit.service
- service: name=monit state=restarted

- timezone: name=America/New_York
