- apt: name={{item}} state=latest force=yes
  with_items:
  - python
  - python-rpi.gpio
  - python-pygame
  - rsync
  - monit

- synchronize: src={{repodir}}/{{item}} dest=/home/{{ansible_ssh_user}}/
  with_items:
  - SOUND_ATTRIBUTION.md
  - sound
  - README.md
  - logging.conf
  - LICENSE.txt
  - lib
  - doorbell.py
  - doorbell_config.ini

# fix audio hiss
- lineinfile: dest=/boot/config.txt state=present line=disable_audio_dither=1
